# Get all notes PUBLIC

GET http://localhost:3001/api/notes

###
# Get a note by ID - PUBLIC

GET http://localhost:3001/api/notes/605bef7921647333073254b3

###
# Delete a single note by id PRIVATE

DELETE http://localhost:3001/api/notes/6088eaadb2c3b735a6afdcc6 HTTP/1.1

###
# Create a note

POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwOGFiMTI0ZWFkN2VmMGNmNWNkMTg1YyIsInVzZXJuYW1lIjoicGFibGV0cyIsImlhdCI6MTYxOTcwMjA3M30.HlkGTPfbQqqcST1IRijdSsEe5ZWSowYRxL7OSnkvmdU

{
    "content": "Otra nota importante",
    "important": true
}

###
# Update a note

PUT http://localhost:3001/api/notes/605cb7b916b56407d16a9a52 HTTP/1.1
Content-Type: application/json

{
    "content": "Actualizando esta nota",
    "important": true
}


